-   repo: https://github.com/Showcase-Insights/pre-commit-golang
    rev: master 
    hooks:
      - id: go-fmt
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy